name: Build and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [ubuntu-latest]


    steps:
      - run: echo "Hello $(arch)"
