name: Build and Upload Artifact

env:
  VERSION: 0.1

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64, aarch64]
        include:
          - platform: x86_64
            image: i386/python:3.11.3-slim
          - platform: aarch64
            image: arm64v8/python:3.11.3-slim
    steps:
      - name: Checkout scripts repository
        uses: actions/checkout@v4
        with:
          repository: PixysOS-Infrastructure/scripts
          token: ${{ secrets.GH_TOKEN }}
          path: '${{ github.workspace }}/ws'
          ref: 'master'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Build
        run: |
          docker run --rm --platform ${{ matrix.platform }} --volume "${{ github.workspace }}/ws/cli/temp-cli:/ws" ${{ matrix.image }} /bin/sh -c " \
            cd ws
            pip3 install --no-cache-dir -r requirements.txt
            pyinstaller -n pixys-cli.${{ env.VERSION }}.${{ matrix.platform }} --onefile standalone_post_build.py
            ls 
            ls dist
          "
        
        
      # - name: Set up Docker BuildX
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Install PIP Dependencies
      #   working-directory: ${{ github.workspace }}/cli/temp-cli
      #   run: 'pip3 install --no-cache-dir -r requirements.txt'
          
